### ISSUE TITLE
golang.org/x/crypto dep should uptdae

### ISSUE THREAD

**Issue by buffge** [alexedwards/argon2id#2]
Vulnerabilities

DepShield reports that this application's usage of golang.org/x:crypto:0.0.0-20190308221718-c2843e01d9a2 results in the following vulnerability(s):

- (CVSS **5.9**) [[CVE-2019-11840]  Use of Insufficiently Random Values](https://ossindex.sonatype.org/vuln/5121f5ff-9831-44a6-af2e-24f7301d1df7)

**Comment by alexedwards** [comment]
Thanks for this.

This package has golang.org/x/crypto v0.0.0-20190605123033 as a dependency, so I thought that it was a bit strange that this was being flagged.

But it looks like golang.org/x/crypto v0.0.0-20190605123033 has golang.org/x/net v0.0.0-20190404232315 a dependency, which in turn has golang.org/x/crypto v0.0.0-20190308221718 as dependency ([see here](https://github.com/golang/net/blob/491137f692577e390404f177a0515c9f86f79754/go.mod#L6)).

So the fix for this is that the golang.org/x/net dep needs to be upgraded.

I'll keep this open until that happens. 

But it looks like the vuln relates to the golang.org/x/crypto/salsa20 package only, which isn't used by argon2id, so this package isn't actually affected anyway.

**Comment by buffge** [comment]
l use the [sonatype-depshield](https://github.com/marketplace/sonatype-depshield) app ,this issues is it prompt me.
You can try it. Thanks
